export const tierData = [
  // {
  //   name: '마스터 1800 이상 탑',
  //   value: '마스터 1800 이상',
  //   position: 'T',
  //   point: 58.5,
  // },
  // {
  //   name: '마스터 1800 이상 정글',
  //   value: '마스터 1800 이상',
  //   position: 'J',
  //   point: 68.4,
  // },
  // {
  //   name: '마스터 1800 이상 미드',
  //   value: '마스터 1800 이상',
  //   position: 'M',
  //   point: 60.9,
  // },
  // {
  //   name: '마스터 1800 이상 원딜',
  //   value: '마스터 1800 이상',
  //   position: 'A',
  //   point: 62.7,
  // },
  // {
  //   name: '마스터 1800 이상 서폿',
  //   value: '마스터 1800 이상',
  //   position: 'S',
  //   point: 58.2,
  // },
  // {
  //   name: '마스터 1700 ~ 1799 탑',
  //   value: '마스터 1700 ~ 1799',
  //   position: 'T',
  //   point: 58.2,
  // },
  // {
  //   name: '마스터 1700 ~ 1799 정글',
  //   value: '마스터 1700 ~ 1799',
  //   position: 'J',
  //   point: 68.1,
  // },
  // {
  //   name: '마스터 1700 ~ 1799 미드',
  //   value: '마스터 1700 ~ 1799',
  //   position: 'M',
  //   point: 60.5,
  // },
  // {
  //   name: '마스터 1700 ~ 1799 원딜',
  //   value: '마스터 1700 ~ 1799',
  //   position: 'A',
  //   point: 62.6,
  // },
  // {
  //   name: '마스터 1700 ~ 1799 서폿',
  //   value: '마스터 1700 ~ 1799',
  //   position: 'S',
  //   point: 58,
  // },
  // {
  //   name: '마스터 1600 ~ 1699 탑',
  //   value: '마스터 1600 ~ 1699',
  //   position: 'T',
  //   point: 57.9,
  // },
  // {
  //   name: '마스터 1600 ~ 1699 정글',
  //   value: '마스터 1600 ~ 1699',
  //   position: 'J',
  //   point: 67.3,
  // },
  // {
  //   name: '마스터 1600 ~ 1699 미드',
  //   value: '마스터 1600 ~ 1699',
  //   position: 'M',
  //   point: 60.2,
  // },
  // {
  //   name: '마스터 1600 ~ 1699 원딜',
  //   value: '마스터 1600 ~ 1699',
  //   position: 'A',
  //   point: 62.4,
  // },
  // {
  //   name: '마스터 1600 ~ 1699 서폿',
  //   value: '마스터 1600 ~ 1699',
  //   position: 'S',
  //   point: 57.8,
  // },
  // {
  //   name: '마스터 1500 ~ 1599 탑',
  //   value: '마스터 1500 ~ 1599',
  //   position: 'T',
  //   point: 57.5,
  // },
  // {
  //   name: '마스터 1500 ~ 1599 정글',
  //   value: '마스터 1500 ~ 1599',
  //   position: 'J',
  //   point: 66.7,
  // },
  // {
  //   name: '마스터 1500 ~ 1599 미드',
  //   value: '마스터 1500 ~ 1599',
  //   position: 'M',
  //   point: 59.6,
  // },
  // {
  //   name: '마스터 1500 ~ 1599 원딜',
  //   value: '마스터 1500 ~ 1599',
  //   position: 'A',
  //   point: 62.2,
  // },
  // {
  //   name: '마스터 1500 ~ 1599 서폿',
  //   value: '마스터 1500 ~ 1599',
  //   position: 'S',
  //   point: 57.4,
  // },
  // {
  //   name: '마스터 1400 ~ 1499 탑',
  //   value: '마스터 1400 ~ 1499',
  //   position: 'T',
  //   point: 57.0,
  // },
  // {
  //   name: '마스터 1400 ~ 1499 정글',
  //   value: '마스터 1400 ~ 1499',
  //   position: 'J',
  //   point: 65.7,
  // },
  // {
  //   name: '마스터 1400 ~ 1499 미드',
  //   value: '마스터 1400 ~ 1499',
  //   position: 'M',
  //   point: 59.1,
  // },
  // {
  //   name: '마스터 1400 ~ 1499 원딜',
  //   value: '마스터 1400 ~ 1499',
  //   position: 'A',
  //   point: 61.6,
  // },
  // {
  //   name: '마스터 1400 ~ 1499 서폿',
  //   value: '마스터 1400 ~ 1499',
  //   position: 'S',
  //   point: 56.9,
  // },
  // {
  //   name: '마스터 1300 ~ 1399 탑',
  //   value: '마스터 1300 ~ 1399',
  //   position: 'T',
  //   point: 56.5,
  // },
  // {
  //   name: '마스터 1300 ~ 1399 정글',
  //   value: '마스터 1300 ~ 1399',
  //   position: 'J',
  //   point: 65.1,
  // },
  // {
  //   name: '마스터 1300 ~ 1399 미드',
  //   value: '마스터 1300 ~ 1399',
  //   position: 'M',
  //   point: 58.6,
  // },
  // {
  //   name: '마스터 1300 ~ 1399 원딜',
  //   value: '마스터 1300 ~ 1399',
  //   position: 'A',
  //   point: 61.4,
  // },
  // {
  //   name: '마스터 1300 ~ 1399 서폿',
  //   value: '마스터 1300 ~ 1399',
  //   position: 'S',
  //   point: 56.6,
  // },
  // {
  //   name: '마스터 1200 ~ 1299 탑',
  //   value: '마스터 1200 ~ 1299',
  //   position: 'T',
  //   point: 55.9,
  // },
  // {
  //   name: '마스터 1200 ~ 1299 정글',
  //   value: '마스터 1200 ~ 1299',
  //   position: 'J',
  //   point: 63.7,
  // },
  // {
  //   name: '마스터 1200 ~ 1299 미드',
  //   value: '마스터 1200 ~ 1299',
  //   position: 'M',
  //   point: 58.4,
  // },
  // {
  //   name: '마스터 1200 ~ 1299 원딜',
  //   value: '마스터 1200 ~ 1299',
  //   position: 'A',
  //   point: 60.7,
  // },
  // {
  //   name: '마스터 1200 ~ 1299 서폿',
  //   value: '마스터 1200 ~ 1299',
  //   position: 'S',
  //   point: 56.2,
  // },
  // {
  //   name: '마스터 1100 ~ 1199 탑',
  //   value: '마스터 1100 ~ 1199',
  //   position: 'T',
  //   point: 55.3,
  // },
  // {
  //   name: '마스터 1100 ~ 1199 정글',
  //   value: '마스터 1100 ~ 1199',
  //   position: 'J',
  //   point: 62.7,
  // },
  // {
  //   name: '마스터 1100 ~ 1199 미드',
  //   value: '마스터 1100 ~ 1199',
  //   position: 'M',
  //   point: 58.1,
  // },
  // {
  //   name: '마스터 1100 ~ 1199 원딜',
  //   value: '마스터 1100 ~ 1199',
  //   position: 'A',
  //   point: 60.2,
  // },
  // {
  //   name: '마스터 1100 ~ 1199 서폿',
  //   value: '마스터 1100 ~ 1199',
  //   position: 'S',
  //   point: 55.7,
  // },
  // {
  //   name: '마스터 1000 ~ 1099 탑',
  //   value: '마스터 1000 ~ 1099',
  //   position: 'T',
  //   point: 54.7,
  // },
  // {
  //   name: '마스터 1000 ~ 1099 정글',
  //   value: '마스터 1000 ~ 1099',
  //   position: 'J',
  //   point: 61.3,
  // },
  // {
  //   name: '마스터 1000 ~ 1099 미드',
  //   value: '마스터 1000 ~ 1099',
  //   position: 'M',
  //   point: 57.6,
  // },
  // {
  //   name: '마스터 1000 ~ 1099 원딜',
  //   value: '마스터 1000 ~ 1099',
  //   position: 'A',
  //   point: 59.3,
  // },
  // {
  //   name: '마스터 1000 ~ 1099 서폿',
  //   value: '마스터 1000 ~ 1099',
  //   position: 'S',
  //   point: 55.1,
  // },
  // {
  //   name: '마스터 900 ~ 999 탑',
  //   value: '마스터 900 ~ 999',
  //   position: 'T',
  //   point: 53.9,
  // },
  // {
  //   name: '마스터 900 ~ 999 정글',
  //   value: '마스터 900 ~ 999',
  //   position: 'J',
  //   point: 59.9,
  // },
  // {
  //   name: '마스터 900 ~ 999 미드',
  //   value: '마스터 900 ~ 999',
  //   position: 'M',
  //   point: 56.5,
  // },
  // {
  //   name: '마스터 900 ~ 999 원딜',
  //   value: '마스터 900 ~ 999',
  //   position: 'A',
  //   point: 58.5,
  // },
  // {
  //   name: '마스터 900 ~ 999 서폿',
  //   value: '마스터 900 ~ 999',
  //   position: 'S',
  //   point: 54.4,
  // },
  // {
  //   name: '마스터 800 ~ 899 탑',
  //   value: '마스터 800 ~ 899',
  //   position: 'T',
  //   point: 52.9,
  // },
  // {
  //   name: '마스터 800 ~ 899 정글',
  //   value: '마스터 800 ~ 899',
  //   position: 'J',
  //   point: 58.8,
  // },
  // {
  //   name: '마스터 800 ~ 899 미드',
  //   value: '마스터 800 ~ 899',
  //   position: 'M',
  //   point: 55.6,
  // },
  // {
  //   name: '마스터 800 ~ 899 원딜',
  //   value: '마스터 800 ~ 899',
  //   position: 'A',
  //   point: 57.6,
  // },
  // {
  //   name: '마스터 800 ~ 899 서폿',
  //   value: '마스터 800 ~ 899',
  //   position: 'S',
  //   point: 53.6,
  // },
  // {
  //   name: '마스터 700 ~ 799 탑',
  //   value: '마스터 700 ~ 799',
  //   position: 'T',
  //   point: 52.1,
  // },
  // {
  //   name: '마스터 700 ~ 799 정글',
  //   value: '마스터 700 ~ 799',
  //   position: 'J',
  //   point: 57.6,
  // },
  // {
  //   name: '마스터 700 ~ 799 미드',
  //   value: '마스터 700 ~ 799',
  //   position: 'M',
  //   point: 54.8,
  // },
  // {
  //   name: '마스터 700 ~ 799 원딜',
  //   value: '마스터 700 ~ 799',
  //   position: 'A',
  //   point: 56.8,
  // },
  // {
  //   name: '마스터 700 ~ 799 서폿',
  //   value: '마스터 700 ~ 799',
  //   position: 'S',
  //   point: 52.9,
  // },
  // {
  //   name: '마스터 600 ~ 699 탑',
  //   value: '마스터 600 ~ 699',
  //   position: 'T',
  //   point: 47.2,
  // },
  // {
  //   name: '마스터 600 ~ 699 정글',
  //   value: '마스터 600 ~ 699',
  //   position: 'J',
  //   point: 52.8,
  // },
  // {
  //   name: '마스터 600 ~ 699 미드',
  //   value: '마스터 600 ~ 699',
  //   position: 'M',
  //   point: 50.3,
  // },
  // {
  //   name: '마스터 600 ~ 699 원딜',
  //   value: '마스터 600 ~ 699',
  //   position: 'A',
  //   point: 51.2,
  // },
  // {
  //   name: '마스터 600 ~ 699 서폿',
  //   value: '마스터 600 ~ 699',
  //   position: 'S',
  //   point: 47.3,
  // },
  // {
  //   name: '마스터 500 ~ 599 탑',
  //   value: '마스터 500 ~ 599',
  //   position: 'T',
  //   point: 44.5,
  // },
  // {
  //   name: '마스터 500 ~ 599 정글',
  //   value: '마스터 500 ~ 599',
  //   position: 'J',
  //   point: 49.6,
  // },
  // {
  //   name: '마스터 500 ~ 599 미드',
  //   value: '마스터 500 ~ 599',
  //   position: 'M',
  //   point: 47.4,
  // },
  // {
  //   name: '마스터 500 ~ 599 원딜',
  //   value: '마스터 500 ~ 599',
  //   position: 'A',
  //   point: 48.2,
  // },
  // {
  //   name: '마스터 500 ~ 599 서폿',
  //   value: '마스터 500 ~ 599',
  //   position: 'S',
  //   point: 44.8,
  // },
  // {
  //   name: '마스터 400 ~ 499 탑',
  //   value: '마스터 400 ~ 499',
  //   position: 'T',
  //   point: 43.0,
  // },
  // {
  //   name: '마스터 400 ~ 499 정글',
  //   value: '마스터 400 ~ 499',
  //   position: 'J',
  //   point: 47.3,
  // },
  // {
  //   name: '마스터 400 ~ 499 미드',
  //   value: '마스터 400 ~ 499',
  //   position: 'M',
  //   point: 45.9,
  // },
  // {
  //   name: '마스터 400 ~ 499 원딜',
  //   value: '마스터 400 ~ 499',
  //   position: 'A',
  //   point: 46.1,
  // },
  // {
  //   name: '마스터 400 ~ 499 서폿',
  //   value: '마스터 400 ~ 499',
  //   position: 'S',
  //   point: 43.2,
  // },
  // {
  //   name: '마스터 300 ~ 399 탑',
  //   value: '마스터 300 ~ 399',
  //   position: 'T',
  //   point: 42.6,
  // },
  // {
  //   name: '마스터 300 ~ 399 정글',
  //   value: '마스터 300 ~ 399',
  //   position: 'J',
  //   point: 44.1,
  // },
  // {
  //   name: '마스터 300 ~ 399 미드',
  //   value: '마스터 300 ~ 399',
  //   position: 'M',
  //   point: 45.1,
  // },
  // {
  //   name: '마스터 300 ~ 399 원딜',
  //   value: '마스터 300 ~ 399',
  //   position: 'A',
  //   point: 39.5,
  // },
  // {
  //   name: '마스터 300 ~ 399 서폿',
  //   value: '마스터 300 ~ 399',
  //   position: 'S',
  //   point: 39.4,
  // },
  // {
  //   name: '마스터 200 ~ 299 탑',
  //   value: '마스터 200 ~ 299',
  //   position: 'T',
  //   point: 40.7,
  // },
  // {
  //   name: '마스터 200 ~ 299 정글',
  //   value: '마스터 200 ~ 299',
  //   position: 'J',
  //   point: 42.2,
  // },
  // {
  //   name: '마스터 200 ~ 299 미드',
  //   value: '마스터 200 ~ 299',
  //   position: 'M',
  //   point: 43.3,
  // },
  // {
  //   name: '마스터 200 ~ 299 원딜',
  //   value: '마스터 200 ~ 299',
  //   position: 'A',
  //   point: 37.3,
  // },
  // {
  //   name: '마스터 200 ~ 299 서폿',
  //   value: '마스터 200 ~ 299',
  //   position: 'S',
  //   point: 38.2,
  // },
  // {
  //   name: '마스터 100 ~ 199 탑',
  //   value: '마스터 100 ~ 199',
  //   position: 'T',
  //   point: 39.2,
  // },
  // {
  //   name: '마스터 100 ~ 199 정글',
  //   value: '마스터 100 ~ 199',
  //   position: 'J',
  //   point: 40.2,
  // },
  // {
  //   name: '마스터 100 ~ 199 미드',
  //   value: '마스터 100 ~ 199',
  //   position: 'M',
  //   point: 40.2,
  // },
  // {
  //   name: '마스터 100 ~ 199 원딜',
  //   value: '마스터 100 ~ 199',
  //   position: 'A',
  //   point: 35.8,
  // },
  // {
  //   name: '마스터 100 ~ 199 서폿',
  //   value: '마스터 100 ~ 199',
  //   position: 'S',
  //   point: 37.1,
  // },
  // {
  //   name: '마스터 0 ~ 99 탑',
  //   value: '마스터 0 ~ 99',
  //   position: 'T',
  //   point: 37.7,
  // },
  // {
  //   name: '마스터 0 ~ 99 정글',
  //   value: '마스터 0 ~ 99',
  //   position: 'J',
  //   point: 39.6,
  // },
  // {
  //   name: '마스터 0 ~ 99 미드',
  //   value: '마스터 0 ~ 99',
  //   position: 'M',
  //   point: 40.8,
  // },
  // {
  //   name: '마스터 0 ~ 99 원딜',
  //   value: '마스터 0 ~ 99',
  //   position: 'A',
  //   point: 34.4,
  // },
  // {
  //   name: '마스터 0 ~ 99 서폿',
  //   value: '마스터 0 ~ 99',
  //   position: 'S',
  //   point: 36.1,
  // },
  {
    name: '마스터 탑',
    value: '마스터',
    position: 'T',
    point: 37.7,
  },
  {
    name: '마스터 정글',
    value: '마스터',
    position: 'J',
    point: 39.6,
  },
  {
    name: '마스터 미드',
    value: '마스터',
    position: 'M',
    point: 40.8,
  },
  {
    name: '마스터 원딜',
    value: '마스터',
    position: 'A',
    point: 34.4,
  },
  {
    name: '마스터 서폿',
    value: '마스터',
    position: 'S',
    point: 36.1,
  },
  {
    name: '다이아몬드1 탑',
    value: '다이아몬드1',
    position: 'T',
    point: 36.2,
  },
  {
    name: '다이아몬드1 정글',
    value: '다이아몬드1',
    position: 'J',
    point: 38.1,
  },
  {
    name: '다이아몬드1 미드',
    value: '다이아몬드1',
    position: 'M',
    point: 38.5,
  },
  {
    name: '다이아몬드1 원딜',
    value: '다이아몬드1',
    position: 'A',
    point: 33,
  },
  {
    name: '다이아몬드1 서폿',
    value: '다이아몬드1',
    position: 'S',
    point: 35,
  },
  {
    name: '다이아몬드2 탑',
    value: '다이아몬드2',
    position: 'T',
    point: 34.7,
  },
  {
    name: '다이아몬드2 정글',
    value: '다이아몬드2',
    position: 'J',
    point: 36.8,
  },
  {
    name: '다이아몬드2 미드',
    value: '다이아몬드2',
    position: 'M',
    point: 37.1,
  },
  {
    name: '다이아몬드2 원딜',
    value: '다이아몬드2',
    position: 'A',
    point: 31.4,
  },
  {
    name: '다이아몬드2 서폿',
    value: '다이아몬드2',
    position: 'S',
    point: 33.4,
  },
  {
    name: '다이아몬드3 탑',
    value: '다이아몬드3',
    position: 'T',
    point: 32.1,
  },
  {
    name: '다이아몬드3 정글',
    value: '다이아몬드3',
    position: 'J',
    point: 33.7,
  },
  {
    name: '다이아몬드3 미드',
    value: '다이아몬드3',
    position: 'M',
    point: 35.5,
  },
  {
    name: '다이아몬드3 원딜',
    value: '다이아몬드3',
    position: 'A',
    point: 28.9,
  },
  {
    name: '다이아몬드3 서폿',
    value: '다이아몬드3',
    position: 'S',
    point: 31.2,
  },
  {
    name: '다이아몬드4 탑',
    value: '다이아몬드4',
    position: 'T',
    point: 30.4,
  },
  {
    name: '다이아몬드4 정글',
    value: '다이아몬드4',
    position: 'J',
    point: 31.8,
  },
  {
    name: '다이아몬드4 미드',
    value: '다이아몬드4',
    position: 'M',
    point: 33.7,
  },
  {
    name: '다이아몬드4 원딜',
    value: '다이아몬드4',
    position: 'A',
    point: 26.9,
  },
  {
    name: '다이아몬드4 서폿',
    value: '다이아몬드4',
    position: 'S',
    point: 29.7,
  },
  {
    name: '에메랄드1 탑',
    value: '에메랄드1',
    position: 'T',
    point: 28.7,
  },
  {
    name: '에메랄드1 정글',
    value: '에메랄드1',
    position: 'J',
    point: 30.1,
  },
  {
    name: '에메랄드1 미드',
    value: '에메랄드1',
    position: 'M',
    point: 31.8,
  },
  {
    name: '에메랄드1 원딜',
    value: '에메랄드1',
    position: 'A',
    point: 25.1,
  },
  {
    name: '에메랄드1 서폿',
    value: '에메랄드1',
    position: 'S',
    point: 28.1,
  },
  {
    name: '에메랄드2 탑',
    value: '에메랄드2',
    position: 'T',
    point: 27.2,
  },
  {
    name: '에메랄드2 정글',
    value: '에메랄드2',
    position: 'J',
    point: 27.5,
  },
  {
    name: '에메랄드2 미드',
    value: '에메랄드2',
    position: 'M',
    point: 29.8,
  },
  {
    name: '에메랄드2 원딜',
    value: '에메랄드2',
    position: 'A',
    point: 23.6,
  },
  {
    name: '에메랄드2 서폿',
    value: '에메랄드2',
    position: 'S',
    point: 26.4,
  },
  {
    name: '에메랄드3 탑',
    value: '에메랄드3',
    position: 'T',
    point: 25.8,
  },
  {
    name: '에메랄드3 정글',
    value: '에메랄드3',
    position: 'J',
    point: 26.1,
  },
  {
    name: '에메랄드3 미드',
    value: '에메랄드3',
    position: 'M',
    point: 28.5,
  },
  {
    name: '에메랄드3 원딜',
    value: '에메랄드3',
    position: 'A',
    point: 22.3,
  },
  {
    name: '에메랄드3 서폿',
    value: '에메랄드3',
    position: 'S',
    point: 27.9,
  },
  {
    name: '에메랄드4 탑',
    value: '에메랄드4',
    position: 'T',
    point: 24.7,
  },
  {
    name: '에메랄드4 정글',
    value: '에메랄드4',
    position: 'J',
    point: 24.4,
  },
  {
    name: '에메랄드4 미드',
    value: '에메랄드4',
    position: 'M',
    point: 27,
  },
  {
    name: '에메랄드4 원딜',
    value: '에메랄드4',
    position: 'A',
    point: 21.1,
  },
  {
    name: '에메랄드4 서폿',
    value: '에메랄드4',
    position: 'S',
    point: 26.2,
  },
  {
    name: '플래티넘1 탑',
    value: '플래티넘1',
    position: 'T',
    point: 23.1,
  },
  {
    name: '플래티넘1 정글',
    value: '플래티넘1',
    position: 'J',
    point: 22.9,
  },
  {
    name: '플래티넘1 미드',
    value: '플래티넘1',
    position: 'M',
    point: 24.5,
  },
  {
    name: '플래티넘1 원딜',
    value: '플래티넘1',
    position: 'A',
    point: 19.8,
  },
  {
    name: '플래티넘1 서폿',
    value: '플래티넘1',
    position: 'S',
    point: 23.2,
  },
  {
    name: '플래티넘2 탑',
    value: '플래티넘2',
    position: 'T',
    point: 22.1,
  },
  {
    name: '플래티넘2 정글',
    value: '플래티넘2',
    position: 'J',
    point: 21.1,
  },
  {
    name: '플래티넘2 미드',
    value: '플래티넘2',
    position: 'M',
    point: 20.8,
  },
  {
    name: '플래티넘2 원딜',
    value: '플래티넘2',
    position: 'A',
    point: 18.3,
  },
  {
    name: '플래티넘2 서폿',
    value: '플래티넘2',
    position: 'S',
    point: 21.4,
  },
  {
    name: '플래티넘3 탑',
    value: '플래티넘3',
    position: 'T',
    point: 21.3,
  },
  {
    name: '플래티넘3 정글',
    value: '플래티넘3',
    position: 'J',
    point: 19.3,
  },
  {
    name: '플래티넘3 미드',
    value: '플래티넘3',
    position: 'M',
    point: 19.2,
  },
  {
    name: '플래티넘3 원딜',
    value: '플래티넘3',
    position: 'A',
    point: 17.2,
  },
  {
    name: '플래티넘3 서폿',
    value: '플래티넘3',
    position: 'S',
    point: 19.7,
  },
  {
    name: '플래티넘4 탑',
    value: '플래티넘4',
    position: 'T',
    point: 20.4,
  },
  {
    name: '플래티넘4 정글',
    value: '플래티넘4',
    position: 'J',
    point: 18.1,
  },
  {
    name: '플래티넘4 미드',
    value: '플래티넘4',
    position: 'M',
    point: 18.2,
  },
  {
    name: '플래티넘4 원딜',
    value: '플래티넘4',
    position: 'A',
    point: 16.2,
  },
  {
    name: '플래티넘4 서폿',
    value: '플래티넘4',
    position: 'S',
    point: 18.3,
  },
  {
    name: '골드1 탑',
    value: '골드1',
    position: 'T',
    point: 19.6,
  },
  {
    name: '골드1 정글',
    value: '골드1',
    position: 'J',
    point: 17.5,
  },
  {
    name: '골드1 미드',
    value: '골드1',
    position: 'M',
    point: 16.3,
  },
  {
    name: '골드1 원딜',
    value: '골드1',
    position: 'A',
    point: 14.9,
  },
  {
    name: '골드1 서폿',
    value: '골드1',
    position: 'S',
    point: 17.2,
  },
  {
    name: '골드2 탑',
    value: '골드2',
    position: 'T',
    point: 18,
  },
  {
    name: '골드2 정글',
    value: '골드2',
    position: 'J',
    point: 15.5,
  },
  {
    name: '골드2 미드',
    value: '골드2',
    position: 'M',
    point: 14.5,
  },
  {
    name: '골드2 원딜',
    value: '골드2',
    position: 'A',
    point: 13.5,
  },
  {
    name: '골드2 서폿',
    value: '골드2',
    position: 'S',
    point: 15.9,
  },
  {
    name: '골드3 탑',
    value: '골드3',
    position: 'T',
    point: 17.2,
  },
  {
    name: '골드3 정글',
    value: '골드3',
    position: 'J',
    point: 14.2,
  },
  {
    name: '골드3 미드',
    value: '골드3',
    position: 'M',
    point: 13.4,
  },
  {
    name: '골드3 원딜',
    value: '골드3',
    position: 'A',
    point: 12.3,
  },
  {
    name: '골드3 서폿',
    value: '골드3',
    position: 'S',
    point: 14.4,
  },
  {
    name: '골드4 탑',
    value: '골드4',
    position: 'T',
    point: 16.4,
  },
  {
    name: '골드4 정글',
    value: '골드4',
    position: 'J',
    point: 13.1,
  },
  {
    name: '골드4 미드',
    value: '골드4',
    position: 'M',
    point: 11.8,
  },
  {
    name: '골드4 원딜',
    value: '골드4',
    position: 'A',
    point: 11.3,
  },
  {
    name: '골드4 서폿',
    value: '골드4',
    position: 'S',
    point: 13.2,
  },
  {
    name: '실버1 탑',
    value: '실버1',
    position: 'T',
    point: 15.8,
  },
  {
    name: '실버1 정글',
    value: '실버1',
    position: 'J',
    point: 12.1,
  },
  {
    name: '실버1 미드',
    value: '실버1',
    position: 'M',
    point: 10.8,
  },
  {
    name: '실버1 원딜',
    value: '실버1',
    position: 'A',
    point: 10.6,
  },
  {
    name: '실버1 서폿',
    value: '실버1',
    position: 'S',
    point: 12.5,
  },
  {
    name: '실버2 탑',
    value: '실버2',
    position: 'T',
    point: 15,
  },
  {
    name: '실버2 정글',
    value: '실버2',
    position: 'J',
    point: 11.8,
  },
  {
    name: '실버2 미드',
    value: '실버2',
    position: 'M',
    point: 10.1,
  },
  {
    name: '실버2 원딜',
    value: '실버2',
    position: 'A',
    point: 10.2,
  },
  {
    name: '실버2 서폿',
    value: '실버2',
    position: 'S',
    point: 11.6,
  },
  {
    name: '실버3 탑',
    value: '실버3',
    position: 'T',
    point: 14,
  },
  {
    name: '실버3 정글',
    value: '실버3',
    position: 'J',
    point: 10,
  },
  {
    name: '실버3 미드',
    value: '실버3',
    position: 'M',
    point: 10,
  },
  {
    name: '실버3 원딜',
    value: '실버3',
    position: 'A',
    point: 10,
  },
  {
    name: '실버3 서폿',
    value: '실버3',
    position: 'S',
    point: 10,
  },
  {
    name: '실버4 탑',
    value: '실버4',
    position: 'T',
    point: 13,
  },
  {
    name: '실버4 정글',
    value: '실버4',
    position: 'J',
    point: 9,
  },
  {
    name: '실버4 미드',
    value: '실버4',
    position: 'M',
    point: 9,
  },
  {
    name: '실버4 원딜',
    value: '실버4',
    position: 'A',
    point: 9,
  },
  {
    name: '실버4 서폿',
    value: '실버4',
    position: 'S',
    point: 9,
  },
  {
    name: '브론즈1 탑',
    value: '브론즈1',
    position: 'T',
    point: 12,
  },
  {
    name: '브론즈1 정글',
    value: '브론즈1',
    position: 'J',
    point: 8,
  },
  {
    name: '브론즈1 미드',
    value: '브론즈1',
    position: 'M',
    point: 8,
  },
  {
    name: '브론즈1 원딜',
    value: '브론즈1',
    position: 'A',
    point: 8,
  },
  {
    name: '브론즈1 서폿',
    value: '브론즈1',
    position: 'S',
    point: 8,
  },
  {
    name: '브론즈2 탑',
    value: '브론즈2',
    position: 'T',
    point: 11,
  },
  {
    name: '브론즈2 정글',
    value: '브론즈2',
    position: 'J',
    point: 7,
  },
  {
    name: '브론즈2 미드',
    value: '브론즈2',
    position: 'M',
    point: 7,
  },
  {
    name: '브론즈2 원딜',
    value: '브론즈2',
    position: 'A',
    point: 7,
  },
  {
    name: '브론즈2 서폿',
    value: '브론즈2',
    position: 'S',
    point: 7,
  },
  {
    name: '브론즈3 탑',
    value: '브론즈3',
    position: 'T',
    point: 10,
  },
  {
    name: '브론즈3 정글',
    value: '브론즈3',
    position: 'J',
    point: 6,
  },
  {
    name: '브론즈3 미드',
    value: '브론즈3',
    position: 'M',
    point: 6,
  },
  {
    name: '브론즈3 원딜',
    value: '브론즈3',
    position: 'A',
    point: 6,
  },
  {
    name: '브론즈3 서폿',
    value: '브론즈3',
    position: 'S',
    point: 6,
  },
  {
    name: '브론즈4 탑',
    value: '브론즈4',
    position: 'T',
    point: 9,
  },
  {
    name: '브론즈4 정글',
    value: '브론즈4',
    position: 'J',
    point: 5,
  },
  {
    name: '브론즈4 미드',
    value: '브론즈4',
    position: 'M',
    point: 5,
  },
  {
    name: '브론즈4 원딜',
    value: '브론즈4',
    position: 'A',
    point: 5,
  },
  {
    name: '브론즈4 서폿',
    value: '브론즈4',
    position: 'S',
    point: 5,
  },
  {
    name: '아이언1 탑',
    value: '아이언1',
    position: 'T',
    point: 8,
  },
  {
    name: '아이언1 정글',
    value: '아이언1',
    position: 'J',
    point: 4,
  },
  {
    name: '아이언1 미드',
    value: '아이언1',
    position: 'M',
    point: 4,
  },
  {
    name: '아이언1 원딜',
    value: '아이언1',
    position: 'A',
    point: 4,
  },
  {
    name: '아이언1 서폿',
    value: '아이언1',
    position: 'S',
    point: 4,
  },
  {
    name: '아이언2 탑',
    value: '아이언2',
    position: 'T',
    point: 7,
  },
  {
    name: '아이언2 정글',
    value: '아이언2',
    position: 'J',
    point: 3,
  },
  {
    name: '아이언2 미드',
    value: '아이언2',
    position: 'M',
    point: 3,
  },
  {
    name: '아이언2 원딜',
    value: '아이언2',
    position: 'A',
    point: 3,
  },
  {
    name: '아이언2 서폿',
    value: '아이언2',
    position: 'S',
    point: 3,
  },
  {
    name: '아이언3 탑',
    value: '아이언3',
    position: 'T',
    point: 6,
  },
  {
    name: '아이언3 정글',
    value: '아이언3',
    position: 'J',
    point: 2,
  },
  {
    name: '아이언3 미드',
    value: '아이언3',
    position: 'M',
    point: 2,
  },
  {
    name: '아이언3 원딜',
    value: '아이언3',
    position: 'A',
    point: 2,
  },
  {
    name: '아이언3 서폿',
    value: '아이언3',
    position: 'S',
    point: 2,
  },
  {
    name: '아이언4 탑',
    value: '아이언4',
    position: 'T',
    point: 5,
  },
  {
    name: '아이언4 정글',
    value: '아이언4',
    position: 'J',
    point: 1,
  },
  {
    name: '아이언4 미드',
    value: '아이언4',
    position: 'M',
    point: 1,
  },
  {
    name: '아이언4 원딜',
    value: '아이언4',
    position: 'A',
    point: 1,
  },
  {
    name: '아이언4 서폿',
    value: '아이언4',
    position: 'S',
    point: 1,
  },
];
